### ISSUE TITLE
Auto reconnect does not work with authentication or if the reconnect max attempts is set to -1

### ISSUE THREAD

**Issue by mariusstaicu** [emqx/mqtt-jmeter#136]
When trying to use auto reconnect feature with the mqtt-plugin, it does not work for the hivemq client implementation in the following 2 scenarios:
1. when setting max reconnect attempts to -1 (infinite) it does not work because of this piece of code in HiveMQTTClient:

```java
    if (parameters.getReconnectMaxAttempts() > 0) {
        builder = builder.automaticReconnectWithDefaultConfig();
    }
```

2. when using authentication, the mqtt reconnector does not inherit the credentials used at the initial connection, because those are set when connection is made and not when client is initially configured. 
In order for the MqttClientReconnector to inherit the authentication, it is necessary to configure authentication prior to configuring the automatic reconnect.

**Comment by chongyuanyin** [comment]
Thanks!
