### ISSUE TITLE
The MQTT Connect Sampler Protocols is missing the 'Trust Key Store(*.jks)' input field

### ISSUE THREAD

**Issue by rogiersb** [emqx/mqtt-jmeter#139]
How to reproduce:
- install the latest jmeter (5.5)
- copy mqtt-xmeter-2.0.2-jar-with-dependencies.jar to the /lib/ext folder and restart jmeter
- add a MQTT Connect sampler to your Test Plan
- go to the Protocols section
- the input field "Trust Key Store(*.jks) is missing

Expected behaviour:
![image](https://user-images.githubusercontent.com/104753672/229042651-71e0da29-852e-4f39-b60b-19246df4387f.png)

Current behaviour:
![image](https://user-images.githubusercontent.com/104753672/229042785-c9f60866-0c11-444f-9470-46b53782f7c6.png)

**Comment by rogiersb** [comment]
I was able to connect by only using a p12/pfx file which contains:
- the TLS client Certificate
- the private key

So please modify the above screenshot in the description that only the p12/pfx file is enough (because it is misleading)

**Comment by chongyuanyin** [comment]
Thanks, we'll update the README.
