### ISSUE TITLE
MQTT v5.0 support for jmeter plugin

### ISSUE THREAD

**Issue by somanivardan** [emqx/mqtt-jmeter#142]
With latest MQTT version v5, there are features to retrieve any information from the userProperties defined for MQTT message.
However, currently MQTT jar for jmeter supports v3.1 and v3.1.1 only and there is no support for MQTT v5.

Is it possible to have a jmeter plugin/jar that supports MQTT v5 so as to use features to read custom information from MQTT message using userproperties?

**Comment by chongyuanyin** [comment]
MQTT 5.0 support is on our planning list. We'll let you know once it's available. Thanks.
