### ISSUE TITLE
need callback functionality

### ISSUE THREAD

**Issue by Hmm90** [emqx/mqtt-jmeter#30]
Hello is it possible to add/implemente to usage of callbacks?

Like descripted in.

Using the Callback/Continuation Passing based API
https://github.com/fusesource/mqtt-client

Thx

**Comment by Hmm90** [comment]
Or better need the possibility to see to content of the callback message

**Comment by rende2005** [comment]
@Hmm90 Actually in the "separate_conn" branch of this project, we already applied the "callback" flavor APIs across connect/pub/sub sampler.   With SubSampler, you can still get the messages based on either "time interval" or "count of messages".

Please give it a try at https://github.com/emqtt/mqtt-jmeter/releases/tag/v1.0.1

If this is not what you're looking for, please give us more details on your thoughts. Thanks!

**Comment by Hmm90** [comment]
during MQTT Connect the client is getting a callback with a uuid. Actual it is not possible to see that uuid as callback message.

**Comment by rende2005** [comment]
1. When connecting,  sampler can specify a clientId, a random suffix can be generated if you will (to distinguish each connecting client).  
2. When CallbackConnection instance is created, it's a unique object instance, you can see sampler response message like this: "Connection org.fusesource.mqtt.client.CallbackConnection@70612f5d".

Not clear on the "uuid" concept you mentioned. Where did you see it,  and what is your usage scenario?

**Comment by Hmm90** [comment]
I need the payload of the callnack message mqttMessage.getpayload()  (org.eclipse.paho.client.mqttv3.MqttMessage)

in my case the payload contains a uuid.

**Comment by rende2005** [comment]
We don't expect a callback message during the ordinary mqtt connection setup process.  
If this is your specific scenario, feel free to extend the plugin code on your own.
