### ISSUE TITLE
[4da70e5] sub时会抛出连接断开异常

### ISSUE THREAD

**Issue by PokerDealer** [emqx/mqtt-jmeter#49]
简单的一个connection（ssl 用户名和密码），一个sub
当运行到sub的时候就会报如下异常信息，附上jmeter.log
再复用连接去pub就会失败，需重新创建新连接

Oct 10, 2018 6:43:19 PM net.xmeter.samplers.ConnectSampler$1 debug
信息: MQTT Tracer: Fatal connection failure: %s

[jmeter.log](https://github.com/emqx/mqtt-jmeter/files/2464351/jmeter.log)

**Comment by jinfahua** [comment]
Please make sure your username & password are correct.
