### ISSUE TITLE
The tail bean is full, will create a new bean for it

### ISSUE THREAD

**Issue by PokerDealer** [emqx/mqtt-jmeter#50]
脚本1：建立一次连接之后，循环100次pub消息，断开连接。
脚本2：建立一次连接之后，循环100次sub消息，断开连接，消费的消息数量还未达到100会报如下信息，并且循环未能停止。

“Oct 24, 2018 5:10:45 PM net.xmeter.samplers.SubSampler handleSubBean
INFO: The tail bean is full, will create a new bean for it.”

请求此问题如何解决？

**Comment by jinfahua** [comment]
This is not a problem, you can ignore it.
