### ISSUE TITLE
JTL format broken due to \n (easy fix)

### ISSUE THREAD

**Issue by jevin36** [emqx/mqtt-jmeter#51]
Hi,

in https://github.com/emqx/mqtt-jmeter/blob/master/mqtt_jmeter/src/main/java/net/xmeter/samplers/SubSampler.java Line 193 the following line breaks the csv format of the **result.jtl**.
`String message = MessageFormat.format("Received {0} of message\n.", receivedCount);`

This should be fixed easilly. Regards

**Comment by chongyuanyin** [comment]
Many thanks! We'll apply the fix.
