### ISSUE TITLE
Subscribe and publish in one connection 

### ISSUE THREAD

**Issue by Hmm90** [emqx/mqtt-jmeter#54]
Hello following situation. 

my broker accepts only one connection to the same time from a client. 

Therefore I need to subscribe and publish in one connection. 

But actual I have to have two threads (Thread A to subscribe and Thread B to publish) 

Every thread needs a MQTT Connect step first and followed by the MQTT Sub (thread A) or MQTT Pub (Thread B).

But in my situation only one connection is allowed and the brokes cuts connection of thread a in case of thread b is executed.  For example mqtt.fx creates only on connection for subscribing and publishing.

Is there a possibility or configuration to solve that?

**Comment by Hmm90** [comment]
found way to get it working.

**Comment by Hiteshkikani** [comment]
> found way to get it working.

@Hmm90 can you share how you got this working. I am in the same boat as you :)

**Comment by god-pane** [comment]
@Hmm90 can you share how you got this working. I am in the same boat as you :)

**Comment by Hmm90** [comment]
Ok, it is not really a solution in general and the issue to share it between connection is still existing.

But in my situation I subscribed immediately after the publish without any delay which seems to fast enough for the broker.
