### ISSUE TITLE
DisConnect 不能指定mqtt client断开连接

### ISSUE THREAD

**Issue by god-pane** [emqx/mqtt-jmeter#56]
在写脚本的时候，通常client都会一直连接，做pub和sub， 所以没办法把DisConnect sample写在后面，我们有可能把脚本被强制停止了，下次再来连接的时候发现这个client还没有断开。

**Comment by jinfahua** [comment]
You can add pub & sub sampler into a loop controller.

**Comment by god-pane** [comment]
![image](https://user-images.githubusercontent.com/9427959/51360767-03dcc880-1b08-11e9-8685-815a1c913ad7.png)
zhe这种情况，不好加啦

**Comment by chongyuanyin** [comment]
以后的新功能中我们会考虑实现跨线程组复用MQTT连接，这样DisConnect就可以放在tearDown线程组中，从而实现测试结束时断开连接。
