### ISSUE TITLE
pubsub_unidirection的时候，netty连接出错：unknown source

### ISSUE THREAD

**Issue by BEWINDOWEB** [emqx/mqtt-jmeter#57]
pubsub_unidirection的时候，moquette 0.12：
![image](https://user-images.githubusercontent.com/6178098/51897112-f2899b00-23e8-11e9-91c9-1d10eca3b581.png)

总会出现，无论什么参数

**Comment by jinfahua** [comment]
Is this an error reported at server side?

**Comment by BEWINDOWEB** [comment]
it's moquette's log, not mqtt-jmeter, thanks, close it.
