### ISSUE TITLE
Can't install on Apache Jmeter 5.0

### ISSUE THREAD

**Issue by tnhabib** [emqx/mqtt-jmeter#58]
I tried installing https://github.com/emqx/mqtt-jmeter/releases/download/1.0.1/mqtt-xmeter-1.0.1-jar-with-dependencies.jarmqtt-xmeter-1.0.1-jar-with-dependencies.jar in both $JMETER_HOME/lib/ext and $JMETER_HOME/lib/e

I added a thread group, then tried to add a sampler and could not find the MQTT samplers

**Comment by smallCC** [comment]
if you using homebrew to install jmeter, you can try to put the plugin's jar into `/usr/local/Cellar/jmeter/$version/libexec/lib/ext`.  
[using-homebrew-to-install-and-configure-jmeter-under-mac-osx](https://www.ubik-ingenierie.com/blog/using-homebrew-to-install-and-configure-jmeter-under-mac-osx/)

**Comment by jinfahua** [comment]
it should be work in JMeter 5.0, please check your install procedure.
