### ISSUE TITLE
MQTT connect failed

### ISSUE THREAD

**Issue by ChangXiaoliu** [emqx/mqtt-jmeter#59]
1.set MQTT connect :
ip/port/mqtt version;
Protocols:SSL not choice Dual SSL authentication
2. run jmx,MQTT connect failed ,result :
Mar 12, 2019 9:11:28 PM net.xmeter.samplers.ConnectSampler sample
SEVERE: For input string: ""

**Comment by jinfahua** [comment]
Could you please post your connection sampler screenshot?

**Comment by ChangXiaoliu** [comment]
![JD20190312211155](https://user-images.githubusercontent.com/17492567/54260340-9a2ae900-45a3-11e9-95c0-83578a78b22f.png)

**Comment by jinfahua** [comment]
Could you try constant string with username & password field?

**Comment by ChangXiaoliu** [comment]
userName：ffffff
password:34AD4D042A6ACB25EB0814AD2DFF5BFD5A140DB5
The parameters are correct,and I use another tool called eclipase pho MQTT Utility,and send with these two parameters and *.jks,then connect successfully.

**Comment by jinfahua** [comment]
Could you please delete the jmeter.log and restart JMeter, then re-run the script. Finally attach the jmeter.log to this thread.

**Comment by ChangXiaoliu** [comment]
![JD20190314094000](https://user-images.githubusercontent.com/17492567/54325461-4240c080-463d-11e9-9a8e-0364307381e9.png)

**Comment by jinfahua** [comment]
It seems your "Timeout(s)" field is empty, could you set it to the default value (it should be 10) ?

**Comment by ChangXiaoliu** [comment]
Thank you.
