### ISSUE TITLE
onfailure: peer disconnected during ssl handshake

### ISSUE THREAD

**Issue by BEWINDOWEB** [emqx/mqtt-jmeter#60]
# Detail
i use mqtt-jmeter to test mqtt tcp over ssl, totally 100000 threads, some of it success, some will give:
```
Apr 15, 2019 5:49:01 AM net.xmeter.samplers.ConnectionCallback onFailure
SEVERE: Peer disconnected during ssl handshake
```
the error rate 80% ~90%
# Tried
i've tried change the JDK 1.8 policy jar to unlimit some settings,but it doesn't work.
https://zhidao.baidu.com/question/269144040788752885.html

**Comment by jinfahua** [comment]
How many machines is used for the test? Please be aware of that one network interface of a machine can only support maximum of 65526 connections. So you should prepare at least several machines for your testing. Also, you can refer to [here - Chinese] (https://www.jianshu.com/p/3799302b2b3e) for JMeter optimization.

**Comment by BEWINDOWEB** [comment]
thanks, i've tried it, and i tried the emqx settings, found that it's not the problem is not from linux settings.
it's my java broker project, use LinkedBlockingQueue to cache the netty event, and it cannot deal with so many event in limit time, and jmeter throw the time limit exceed exception.
jmeter is fine.
