### ISSUE TITLE
SSL certificate authentication

### ISSUE THREAD

**Issue by j1122** [emqx/mqtt-jmeter#61]
For Protocols:SSL not Dual SSL authentication, how to configure the jks location?

Was getting "Failed to establish Connection org.fusesource.mqtt.client.CallbackConnection@6f7fcb66" error when try to connect to amq-broker-7.2.2 via SSL connection.

**Comment by jinfahua** [comment]
You don't need to configure JKS, the client accept any certification issued from server. Please check other authentication settings of MQTT connection.

**Comment by j1122** [comment]
What if the client cert is a chained cert like
root ca->intermediate ca->client cert
Will this caused any issue?
My amq-broker setup do not have any other authentication settings beside certification authentication.

**Comment by jinfahua** [comment]
Could you please attach the jmeter.log to this issue? The file is under the folder where you execute the jmeter.

**Comment by j1122** [comment]
Attached please find the log
[jmeter.log](https://github.com/emqx/mqtt-jmeter/files/3087876/jmeter.log)
![conn](https://user-images.githubusercontent.com/20152128/56260252-1ebfd880-6109-11e9-9abd-d77259208c9f.jpg)

**Comment by j1122** [comment]
Sorry, my bad, the service is actually listenning on another interface, so I cant access with the configured destination.
