### ISSUE TITLE
publish message encoding support

### ISSUE THREAD

**Issue by xiaxinkai** [emqx/mqtt-jmeter#65]
Tested Server encoding is UTF-8
I run mqtt-jmeter on Windos10, Simplified Chinese.
When I publish one mqtt message, the payload contains Chinese characters,
then tested server will recieve garbled message.
Can you add message content encoding function into mqtt-jmeter?

**Comment by Eluso** [comment]
Please use jmeter BeanShell PreProcessor to content,Example：

`String datas = vars.get("cid");

byte[] data = datas.getBytes();

char[] HEX_DIGITS_LOWER = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f'};

int l = data.length;

int outLength = l << 1;

char[] out = new char[outLength];
// two characters form the hex value.
for (int i = 0, j = 0; i < l; i++) {
    out[j++] = HEX_DIGITS_LOWER[(0xF0 & data[i]) >> 4];
    out[j++] = HEX_DIGITS_LOWER[0x0F & data[i]];
}

String ccid = String.valueOf(out);

System.out.println(ccid);
vars.put("ccid",ccid);
`

**Comment by xiaxinkai** [comment]
@Eluso Thanks, I have solved the issue.

**Comment by jiujiu009** [comment]
请问怎么解决的？我也遇到这问题了

**Comment by jiujiu009** [comment]
> 测试的服务器编码是UTF-8 我在Windos10上运行mqtt-jmeter，简体中文。 当我发布一条mqtt消息时，负载中包含中文字符， 然后测试的服务器将收到乱码消息。 mqtt-jmeter可以添加消息内容编码功能吗？

大佬。请问怎么解决？

**Comment by wanghengGit** [comment]
<img width="607" alt="1725518745446" src="https://github.com/user-attachments/assets/04f1df3b-63df-465d-8a33-e8e314e88fc4">
处理报文的地方改一下bianm编码，这里建议加一个配置参数到界面
